# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssetKeyValueObjectsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'str',
        'value_object': 'object'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'value_object': 'value_object'
    }

    def __init__(self, timestamp=None, value_object=None):  # noqa: E501
        """AssetKeyValueObjectsData - a model defined in Swagger"""  # noqa: E501
        self._timestamp = None
        self._value_object = None
        self.discriminator = None
        if timestamp is not None:
            self.timestamp = timestamp
        if value_object is not None:
            self.value_object = value_object

    @property
    def timestamp(self):
        """Gets the timestamp of this AssetKeyValueObjectsData.  # noqa: E501

        timestamp of the value  # noqa: E501

        :return: The timestamp of this AssetKeyValueObjectsData.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this AssetKeyValueObjectsData.

        timestamp of the value  # noqa: E501

        :param timestamp: The timestamp of this AssetKeyValueObjectsData.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def value_object(self):
        """Gets the value_object of this AssetKeyValueObjectsData.  # noqa: E501

        value / selected value  # noqa: E501

        :return: The value_object of this AssetKeyValueObjectsData.  # noqa: E501
        :rtype: object
        """
        return self._value_object

    @value_object.setter
    def value_object(self, value_object):
        """Sets the value_object of this AssetKeyValueObjectsData.

        value / selected value  # noqa: E501

        :param value_object: The value_object of this AssetKeyValueObjectsData.  # noqa: E501
        :type: object
        """

        self._value_object = value_object

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetKeyValueObjectsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetKeyValueObjectsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
