# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HealthConditionBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'diagnosis_code': 'str'
    }

    attribute_map = {
        'diagnosis_code': 'diagnosis_code'
    }

    discriminator_value_class_map = {
          'HealthConditionRequest': 'HealthConditionRequest',
'HealthConditionResponse': 'HealthConditionResponse',
'AssetHealthConditionResponse': 'AssetHealthConditionResponse',
'HealthConditionExtended': 'HealthConditionExtended'    }

    def __init__(self, diagnosis_code=None):  # noqa: E501
        """HealthConditionBase - a model defined in Swagger"""  # noqa: E501
        self._diagnosis_code = None
        self.discriminator = 'healthConditionBaseType'
        self.diagnosis_code = diagnosis_code

    @property
    def diagnosis_code(self):
        """Gets the diagnosis_code of this HealthConditionBase.  # noqa: E501

        Diagnosis code of the health condition. Whitespaces are trimmed  # noqa: E501

        :return: The diagnosis_code of this HealthConditionBase.  # noqa: E501
        :rtype: str
        """
        return self._diagnosis_code

    @diagnosis_code.setter
    def diagnosis_code(self, diagnosis_code):
        """Sets the diagnosis_code of this HealthConditionBase.

        Diagnosis code of the health condition. Whitespaces are trimmed  # noqa: E501

        :param diagnosis_code: The diagnosis_code of this HealthConditionBase.  # noqa: E501
        :type: str
        """
        if diagnosis_code is None:
            raise ValueError("Invalid value for `diagnosis_code`, must not be `None`")  # noqa: E501

        self._diagnosis_code = diagnosis_code

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HealthConditionBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HealthConditionBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
