# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NestedIDUserNameHref(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'href': 'str'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'href': 'href'
    }

    def __init__(self, id=None, first_name=None, last_name=None, href=None):  # noqa: E501
        """NestedIDUserNameHref - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._first_name = None
        self._last_name = None
        self._href = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if href is not None:
            self.href = href

    @property
    def id(self):
        """Gets the id of this NestedIDUserNameHref.  # noqa: E501

        ID of the nested resources  # noqa: E501

        :return: The id of this NestedIDUserNameHref.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NestedIDUserNameHref.

        ID of the nested resources  # noqa: E501

        :param id: The id of this NestedIDUserNameHref.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this NestedIDUserNameHref.  # noqa: E501

        email to the user  # noqa: E501

        :return: The first_name of this NestedIDUserNameHref.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this NestedIDUserNameHref.

        email to the user  # noqa: E501

        :param first_name: The first_name of this NestedIDUserNameHref.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this NestedIDUserNameHref.  # noqa: E501

        email to the user  # noqa: E501

        :return: The last_name of this NestedIDUserNameHref.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this NestedIDUserNameHref.

        email to the user  # noqa: E501

        :param last_name: The last_name of this NestedIDUserNameHref.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def href(self):
        """Gets the href of this NestedIDUserNameHref.  # noqa: E501

        href to the nested resource  # noqa: E501

        :return: The href of this NestedIDUserNameHref.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this NestedIDUserNameHref.

        href to the nested resource  # noqa: E501

        :param href: The href of this NestedIDUserNameHref.  # noqa: E501
        :type: str
        """

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NestedIDUserNameHref, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NestedIDUserNameHref):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
