# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SoftwareAttachmentLinkRequestPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'content_date': 'str',
        'remarks': 'str',
        'software': 'NestedID'
    }

    attribute_map = {
        'href': 'href',
        'content_date': 'content_date',
        'remarks': 'remarks',
        'software': 'software'
    }

    def __init__(self, href=None, content_date=None, remarks=None, software=None):  # noqa: E501
        """SoftwareAttachmentLinkRequestPost - a model defined in Swagger"""  # noqa: E501
        self._href = None
        self._content_date = None
        self._remarks = None
        self._software = None
        self.discriminator = None
        self.href = href
        if content_date is not None:
            self.content_date = content_date
        if remarks is not None:
            self.remarks = remarks
        self.software = software

    @property
    def href(self):
        """Gets the href of this SoftwareAttachmentLinkRequestPost.  # noqa: E501

        the link, must be http or https link  # noqa: E501

        :return: The href of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this SoftwareAttachmentLinkRequestPost.

        the link, must be http or https link  # noqa: E501

        :param href: The href of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def content_date(self):
        """Gets the content_date of this SoftwareAttachmentLinkRequestPost.  # noqa: E501

        Last edit date of the file  # noqa: E501

        :return: The content_date of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._content_date

    @content_date.setter
    def content_date(self, content_date):
        """Sets the content_date of this SoftwareAttachmentLinkRequestPost.

        Last edit date of the file  # noqa: E501

        :param content_date: The content_date of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :type: str
        """

        self._content_date = content_date

    @property
    def remarks(self):
        """Gets the remarks of this SoftwareAttachmentLinkRequestPost.  # noqa: E501

        remarks of the software attachment  # noqa: E501

        :return: The remarks of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks):
        """Sets the remarks of this SoftwareAttachmentLinkRequestPost.

        remarks of the software attachment  # noqa: E501

        :param remarks: The remarks of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :type: str
        """

        self._remarks = remarks

    @property
    def software(self):
        """Gets the software of this SoftwareAttachmentLinkRequestPost.  # noqa: E501


        :return: The software of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :rtype: NestedID
        """
        return self._software

    @software.setter
    def software(self, software):
        """Sets the software of this SoftwareAttachmentLinkRequestPost.


        :param software: The software of this SoftwareAttachmentLinkRequestPost.  # noqa: E501
        :type: NestedID
        """
        if software is None:
            raise ValueError("Invalid value for `software`, must not be `None`")  # noqa: E501

        self._software = software

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SoftwareAttachmentLinkRequestPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SoftwareAttachmentLinkRequestPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
