# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubscriptionSeatBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'email': 'str'
    }

    attribute_map = {
        'status': 'status',
        'email': 'email'
    }

    discriminator_value_class_map = {
          'SubscriptionSeatResponse': 'SubscriptionSeatResponse'    }

    def __init__(self, status=None, email=None):  # noqa: E501
        """SubscriptionSeatBase - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._email = None
        self.discriminator = 'subscriptionSeatBaseType'
        if status is not None:
            self.status = status
        if email is not None:
            self.email = email

    @property
    def status(self):
        """Gets the status of this SubscriptionSeatBase.  # noqa: E501

        status of the subscription seat, can be invited, pending, accepted  # noqa: E501

        :return: The status of this SubscriptionSeatBase.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SubscriptionSeatBase.

        status of the subscription seat, can be invited, pending, accepted  # noqa: E501

        :param status: The status of this SubscriptionSeatBase.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def email(self):
        """Gets the email of this SubscriptionSeatBase.  # noqa: E501

        email of users to be invited as new netilion user  # noqa: E501

        :return: The email of this SubscriptionSeatBase.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this SubscriptionSeatBase.

        email of users to be invited as new netilion user  # noqa: E501

        :param email: The email of this SubscriptionSeatBase.  # noqa: E501
        :type: str
        """

        self._email = email

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionSeatBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionSeatBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
